model.loss_config.loss_type: choice("bce_ctcvr")
model.loss_config.loss_weight_list: choice([1, 1], [0.8, 1], [1, 0.8])
model.expert_type: choice("dcnv2")
model.dcnv2_model_structure: choice("stacked")
model.dcnv2_num_cross_layers: choice(1, 2, 3)
model.expert_hidden_units: choice([32, 16, 8], [128, 64, 32])
model.gate_hidden_units: choice([8, 4])
model.tower_hidden_units: choice([8, 4], [2])
model.input_hidden_units: choice([8], [32], [128])
model.num_layers: choice(1, 2)
model.num_shared_experts: choice(1, 2)
model.num_outcome_shared_experts: choice(1)
model.num_treatment_shared_experts: choice(1)
model.num_specific_experts: choice(0)