# @package _global_
dataset:
  max_number: 1000
  random: True

model:
  encoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 128
    seq_hidden_units: 74
    br_size: 74
    fc_hidden_units: 37
    dropout_rate: 0.1
    num_layer: 1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.0001
    batch_size: 512
    br_size: 98
    fc_hidden_units: 98
    dropout_rate: 0.1
    num_layer: 2

exp:
  weights_ema: True
  alpha: 0
  alpha_wass: 0.00001
  alpha_wass_growth: 0.001
  alpha_wass_max: 0.01
  alpha_wass_epoch: False
  balancing: subgroup
  max_epochs: 500
  num_timepoints: 99