# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

# pyre-strict
# @package _global_
dataset:
  coeff: 2.0

model:
  encoder:
    optimizer:
      learning_rate: 0.005
    batch_size: 1024
    seq_hidden_units: 24
    br_size: 24
    fc_hidden_units: 96
    dropout_rate: 0.2

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 4096
    br_size: 24
    fc_hidden_units: 12
    dropout_rate: 0.1

exp:
  weights_ema: True
  alpha: 0
  alpha_wass: 0.0001
  alpha_wass_growth: 0.001
  alpha_wass_max: 0.01
  alpha_wass_epoch: False
  balancing: marginal
  num_timepoints: 59
