# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

# pyre-strict
# @package _global_
dataset:
  coeff: 6.0
  random: False
  noise_percentage: 0.00

model:
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 256
    seq_hidden_units: 24
    br_size: 12 
    fc_hidden_units: 48 
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.00
  beta: 0.99
  alpha_wass: 0.0001
  alpha_wass_growth: 0.001
  alpha_wass_max: 0.01
  alpha_wass_epoch: False
  final_balancing_method: domain_confusion
  initial_balancing_method: domain_confusion
  balancing_switch_epoch: 99
  max_epochs: 100
  clustering_method: GMM
  number_clusters: 2
  num_timepoints: 59
  gap_epoch: 60
  checkpoint_dir: "./checkpoints/cancer/ct/alpha0/6"
