# @package _global_
dataset:
  coeff: 3.0
  random: True
  noise_percentage: 0.05  

model:
  multi:
    optimizer:
      learning_rate: 0.001
    batch_size: 128
    seq_hidden_units: 16
    br_size: 12
    fc_hidden_units: 24
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  alpha_wass: 0.001
  alpha_wass_growth: 0.001
  alpha_wass_max: 0.01
  alpha_wass_epoch: False
  final_balancing_method: subgroup
  initial_balancing_method: domain_confusion
  balancing_switch_epoch: 199
  max_epochs: 220
  clustering_method: GMM
  number_clusters: 2
  num_timepoints: 59
  gap_epoch: 10
  checkpoint_dir: "./checkpoints/cancer/ct/3"