# @package _global_
dataset:
  coeff: 6.0
  random: False
  noise_percentage: 0.00

model:
  multi:
    optimizer:
      learning_rate: 0.02
    batch_size: 1024
    seq_hidden_units: 12
    br_size: 16
    fc_hidden_units: 48
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  alpha_wass: 10
  alpha_wass_growth: 0.001
  alpha_wass_max: 0.01
  alpha_wass_epoch: False
  final_balancing_method: subgroup
  initial_balancing_method: domain_confusion 
  balancing_switch_epoch: 99
  max_epochs: 120
  clustering_method: GMM
  number_clusters: 2
  num_timepoints: 59
  gap_epoch: 10
  seed: 10
  checkpoint_dir: "./checkpoints/cancer/ct/SGA/6"