name: "ECUP"
loss_config:
  loss_type: "bce_ctcvr"
  loss_weight_list: [1, 1]

# Network Components
hidden_units_task: [64, 32]
hidden_units_treatment: [32]
hidden_units_gate: [32]
hidden_units_task_gate: [32]

# Model Parameters
task_dim: 1
num_heads: 2
hidden_activations: "ELU"
net_dropout: 0.1
batch_norm: true
task: "binary_classification" 