name: "MMoE_PS"
loss_config:
  loss_type: "bce"
  loss_weight_list: [1.2, 1]

num_experts: 4
expert_hidden_units: [32, 16, 8] #[512, 256, 128]
gate_hidden_units: [32, 16] #[128, 64]
tower_hidden_units: [64, 32] #[128, 64]
hidden_activations: "ReLU"
net_dropout: 0.2
batch_norm: True
task: binary_classification
