name: "PLE2D"
loss_config:
  loss_type: "bce_ctcvr"
  loss_weight_list: [1, 1]
num_layers: 1
expert_type: "dcnv2"
dcnv2_model_structure: "stacked"
dcnv2_num_cross_layers: 2
num_shared_experts: 1
num_outcome_shared_experts: 1
num_treatment_shared_experts: 1
num_specific_experts: 0
input_hidden_units: [16]
expert_hidden_units: [512, 256, 128]
gate_hidden_units: [128, 64]
tower_hidden_units: [128, 64]
hidden_activations: "ReLU"
net_dropout: 0
batch_norm: False
task: binary_classification
  