# @package _global_
dataset:
  coeff: 4.0

model:
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 1024
    seq_hidden_units: 12
    br_size: 16
    fc_hidden_units: 48
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0
  alpha_wass: 0.001
  alpha_wass_growth: 0.001
  alpha_wass_max: 0.01
  alpha_wass_epoch: False
  balancing: subgroup
  max_epochs: 150
  num_timepoints: 59