# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

# pyre-strict
# @package _global_
dataset:
  coeff: 0.0

model:
  propensity_treatment:
    seq_hidden_units: 6                 # rnn_hidden_units in the original terminology
    dropout_rate: 0.2
    num_layer: 1
    batch_size: 64
    max_grad_norm: 1.0
    optimizer:
      learning_rate: 0.01

  propensity_history:
    seq_hidden_units: 8                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.3
    num_layer: 1
    batch_size: 128
    max_grad_norm: 1.0
    optimizer:
      learning_rate: 0.01

  encoder:
    seq_hidden_units: 12                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.1                       # Dropout of LSTM hidden layers + output layers
    num_layer: 1
    batch_size: 128
    max_grad_norm: 0.5
    optimizer:
      learning_rate: 0.01

  train_decoder: True
  decoder:
    seq_hidden_units: 32                    # rnn_hidden_units in the original terminology
    dropout_rate: 0.2                        # Dropout of LSTM hidden layers + output layers
    num_layer: 1
    batch_size: 1024
    max_grad_norm: 2.0
    optimizer:
      learning_rate: 0.001
